version: 2

seeds:
  - name: seed_common_crawl
    description: A website page's WARC data in table format.
    columns:
      - name: response_headers_status_code
        description: '{{ doc("common_crawl__response_headers_status_code") }}'
        data_type: number
      - name: response_payload
        description: '{{ doc("common_crawl__response_payload") }}'
        data_type: string
      - name: warc_warcinfo_id
        description: '{{ doc("common_crawl__warc_warcinfo_id") }}'
        data_type: string
  - name: seed_country_codes
    description: Snapshot of a source crawl.
    columns:
      - name: country_code
        description: '{{ doc("country_codes__country_code") }}'
        data_type: string
      - name: top_level_domain
        description: '{{ doc("country_codes__top_level_domain") }}'
        data_type: string
