version: '3'

services:
  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password  # Change this to a secure password

  wasm-crawler:
    build:
      context: .
      dockerfile: WASM-Crawler/Dockerfile
    depends_on:
      - couchdb
    environment:
      DATABASE_URL: http://couchdb:5984/npm
    volumes:
      - ${CRAWLER_DATA_PATH}:/app/crawler_data
    command: sh -c 'echo "Wasm crawler is not started. Run it manually." && sleep infinity'
