apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: httpd
    spec:
      containers:
        - image: httpd:2.4.62-alpine
          name: httpd
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: httpd-claim0
      restartPolicy: Always
      volumes:
        - name: httpd-claim0
          persistentVolumeClaim:
            claimName: httpd-claim0
