apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: minio-client
  name: minio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: minio-client
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo ''...waiting...'' && sleep 1; done; /usr/bin/mc mb minio/lakehouse; /usr/bin/mc anonymous set public minio/lakehouse; tail -f /dev/null '
          env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: password
          image: minio/mc
          name: minio-client
      restartPolicy: Always
