apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: spark-iceberg
  name: spark-iceberg
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "10000"
      port: 10000
      targetPort: 10000
    - name: "10001"
      port: 10001
      targetPort: 10001
  selector:
    io.kompose.service: spark-iceberg
