apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: spark-iceberg
  name: spark-iceberg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-iceberg
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yaml -o docker/kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: spark-iceberg
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: password
          image: ghcr.io/dargmuesli/spark-iceberg:3.5.3_1.6.1
          name: spark-iceberg
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 10000
              protocol: TCP
            - containerPort: 10001
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/spark/entrypoint.sh
              name: spark-iceberg-cm0
              subPath: entrypoint.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: entrypoint-master.sh
                path: entrypoint.sh
            name: spark-iceberg-cm0
          name: spark-iceberg-cm0
